CREATE USER webuser WITH ENCRYPTED PASSWORD 'pass';

GRANT ALL PRIVILEGES ON DATABASE todos TO webuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA todos TO webuser;

GRANT CONNECT ON DATABASE todos TO webuser;
GRANT USAGE ON SCHEMA todos TO webuser;