version: '3.3'

# Parameters:
# POSTGRES_USER
# POSTGRES_PASSWORD
# PGADMIN_DEFAULT_EMAIL
# PGADMIN_DEFAULT_PASSWORD
# PGADMIN_PORT
# POSTGRES_DATABASE

services:

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-a@a.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pass}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres

  db-migration:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_migrator
    depends_on: 
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-todos}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge